#!/usr/bin/env node
/**
 * build-engine.js
 *
 * Generates public/chess-engine.js from the four CommonJS source modules:
 *   src/chess.js  src/ai.js  src/pgn.js  src/analysis.js
 *
 * The output is a minified IIFE that exposes window.Chess / window.AI /
 * window.PGN / window.Analysis — identical logic, zero manual sync.
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const { minify } = require('terser');

// ── Module descriptors ────────────────────────────────────────────────────────
// Each module declares which names it exports and which cross-module
// qualified references (e.g. `Chess.deepCopy`) must be collapsed to bare
// names (they all share the same IIFE scope).
const MODULES = [
  {
    file: 'src/chess.js',
    label: 'CHESS ENGINE  (src/chess.js)',
    windowProp: 'Chess',
    exports: [
      'createInitialState', 'getPieceColor', 'isValidMove', 'getAllValidMoves',
      'getValidMovesForPiece', 'makeMove', 'undoMove', 'resign', 'getClientState',
      'isInCheck', 'findKingPos', 'deepCopy', 'positionKey', 'computeBaseNotation',
      'checkDraw', 'coordsToAlgebraic',
    ],
    qualifiedRefs: [],  // no cross-module calls in chess.js
  },
  {
    file: 'src/ai.js',
    label: 'AI  (src/ai.js)',
    windowProp: 'AI',
    exports: [
      'playComputerMove', 'evaluateBoard', 'scoreMoveWithLookahead',
      'applyMoveToBoard', 'makeTempState', 'PIECE_VALUE',
    ],
    // ai.js calls Chess.* — collapse to bare names since they share scope
    qualifiedRefs: ['Chess'],
  },
  {
    file: 'src/pgn.js',
    label: 'PGN  (src/pgn.js)',
    windowProp: 'PGN',
    exports: [
      'importPGN', 'exportPGN', 'parsePGNMoveList', 'parsePGNHeaders',
      'sanToMove', 'snapshotForReview',
    ],
    qualifiedRefs: ['Chess'],
  },
  {
    file: 'src/analysis.js',
    label: 'ANALYSIS  (src/analysis.js)',
    windowProp: 'Analysis',
    exports: ['analyseGame', 'badge'],
    qualifiedRefs: ['Chess', 'AI'],
  },
];

// ── Source transformations ────────────────────────────────────────────────────

function transformSource(src, qualifiedRefs) {
  const lines = src.split('\n');
  const out = [];
  let skipBlock = false;  // inside a module.exports = { ... } block
  let braceDepth = 0;

  for (const line of lines) {
    // Drop 'use strict' — the IIFE wrapper adds it once
    if (/^\s*'use strict';\s*$/.test(line)) continue;

    // Drop require() lines
    if (/^\s*const\s+\w+\s*=\s*require\(/.test(line)) continue;

    // Drop module.exports = { ... } blocks (may span multiple lines)
    if (/^\s*module\.exports\s*=\s*\{/.test(line)) {
      skipBlock = true;
      braceDepth = (line.match(/\{/g) || []).length - (line.match(/\}/g) || []).length;
      if (braceDepth === 0) skipBlock = false;  // single-line (unlikely but safe)
      continue;
    }
    if (skipBlock) {
      braceDepth += (line.match(/\{/g) || []).length - (line.match(/\}/g) || []).length;
      if (braceDepth <= 0) skipBlock = false;
      continue;
    }

    // Collapse qualified references (Chess.foo → foo, AI.foo → foo, etc.)
    let transformed = line;
    for (const ns of qualifiedRefs) {
      transformed = transformed.replace(new RegExp(`\\b${ns}\\.`, 'g'), '');
    }

    // Indent by 2 spaces to sit inside the IIFE
    out.push('  ' + transformed);
  }

  return out.join('\n');
}

// ── Assemble IIFE ─────────────────────────────────────────────────────────────

const sections = [];

for (const mod of MODULES) {
  const src = fs.readFileSync(path.join(__dirname, mod.file), 'utf8');
  const body = transformSource(src, mod.qualifiedRefs);
  sections.push(
    `  // ${'='.repeat(64)}\n` +
    `  // ${mod.label}\n` +
    `  // ${'='.repeat(64)}\n` +
    body
  );
}

// Build window.* export blocks
const exportBlocks = MODULES.map(mod => {
  const props = mod.exports.map(name => `    ${name},`).join('\n');
  return `  window.${mod.windowProp} = {\n${props}\n  };`;
}).join('\n\n');

const banner = `/* chess-engine.js — auto-generated by build-engine.js — DO NOT EDIT */`;

const unminified = [
  '(function (window) {',
  "  'use strict';",
  '',
  sections.join('\n'),
  '',
  exportBlocks,
  '',
  '}(window));',
  '',
].join('\n');

const outPath = path.join(__dirname, 'public', 'chess-engine.js');

minify(unminified, {
  compress: { passes: 2 },
  mangle: true,
  format: { preamble: banner },
}).then(({ code }) => {
  fs.writeFileSync(outPath, code, 'utf8');
  const ratio = ((1 - code.length / unminified.length) * 100).toFixed(1);
  console.log(`Built ${outPath}  ${unminified.length} → ${code.length} bytes  (−${ratio}%)`);
}).catch(err => {
  console.error('Minification failed:', err.message);
  process.exit(1);
});
